### ISSUE TITLE
Calculus Grapher Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/calculus-grapher#1]
## Design
- [x] **Design doc created** (Date: 02/10/2015)
- [x] **Legacy sim docs/info gathered**
- [x] **Learning goals and standards identified** (Date: 02/25/2015)
- [x] **Design concept complete**  (Date: 3/13/2015)
- [x] **Wireframes complete** (Date: 4/23/2015) 
- [x] **Sim folder and design doc created** (Date: //)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Review user feedback** 
   - [x] *If a Port:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=677625918)
   - [ ] ~~*If a new sim:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=898967246)~~
- [x] **Learning goals and standards identified** (Date: //)
- [x] **Design concept complete**  (Date: //)
- [x] **Wireframes complete** (Date: //)
- [x] **Mockups complete** (Date: //)
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: //)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: Mid March 2023)
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items**
  - [x] Auxiliary screenshots (up to 3 additional), tracking in #321
  - [x] Screen-specific screenshots for metadata service (see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827)), tracking in https://github.com/phetsims/calculus-grapher/issues/335
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Accessibility features
  - [x] Email announcement language
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] ~~[LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive~~
  - [ ] ~~[LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)~~
- [x] **Make sim visible on website** 
   - [x] Clear "Metadata caches" on the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage) page
- [x] **Post-publication items**
  - [x] *If a Port:* Review legacy gold star activities, copy over if appropriate
  - [x] Share new features, design challenges, and treats with group!
  - [x] Email announcement
  - [ ] ~~Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)~~
  - [ ] ~Create "sim primer" issue~
  - [ ] ~Hold postmortem if applicable (Date: //)~

## ~~Inclusive Features~~

Not included in 1.0.

## Implementation
- [x] **Sim repo created** (Date: 5/20/2015)
  - [x] Collaborators added (such as 3rd party, QA team, designers, etc) 
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
- [x] **Repository created** by following [new_repo_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/new_repo_checklist.md) (Date: //)
- [x] **Development started** (Date: In earnest, beginning of sept 2022)
- [x] **Sim is "feature complete"** (Date: //)
- [x] **QA team "first look"** (Date: //)
- [x] Interviews may happen around here (see above)
- [x] Code Review checklist completed
- [x] **Sim team sign-off** (Date: //)
- [x] **Code review completed** (Date: 3/16/23)
- [x] **Sim dev test completed** (Date: 3/24/23)
- [x] **Sim RC tests completed** (Date: 4/17/23)
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#screenshots)), tracking in https://github.com/phetsims/calculus-grapher/issues/321
  - [x] Verify credits, tracking in #202
  - [x] ~~Add CT tests for public query parameters~~
- [x] **Published** (Date: 4/17/2023)

## QA
- [x] *If a Port:* **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing started** (Date: 3/20/23)
- [x] **Dev testing completed** (Date: 3/24/23)
- [x] **First RC published** (Date: 3/28/23)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 4/17/2023)

**Comment by arouinfar** [comment]
When updating sim checklists in https://github.com/phetsims/phet-info/issues/189, I skipped this one because it looks like it's quite out of date. Whenever work on this sim resumes, I recommend converting this over to the [latest template](https://github.com/phetsims/phet-info/blob/master/checklists/sim_checklist.md).

**Comment by veillette** [comment]
The checklist was converted to the latest template and the milestones that were achieved have been incorporated into the checklist.(9/7/2022)

**Comment by veillette** [comment]
Code review was completed  and comments were addressed  (second week of march 2023)

**Comment by veillette** [comment]
Sim RC tests completed on Monday 4/4/2023.

**Comment by pixelzoom** [comment]
> Sim RC tests completed on Monday 4/4/2023.

Not quite. RC1 test completed, but we still need to complete at least RC2.

**Comment by veillette** [comment]
The testing on RC.2 is completed https://github.com/phetsims/qa/issues/933

**Comment by veillette** [comment]
The simulation was published on 4/18/2023.

**Comment by pixelzoom** [comment]
The remaining checklist items are for @amanda-phet, so unassigning others.

**Comment by amanda-phet** [comment]
All looks good to me. Closing!
